### ISSUE TITLE
Configuration does not work for Delong batteries

### ISSUE THREAD

**Issue by Algram** [syssi/esphome-pace-bms#16]
Hi,

I have a battery pack from "Titan Solar" which uses the Pace BMS and Delong batteries. I can't get it to successfully communicate with the ESP32. I am using a RS485 converter with flow control, but I never get a response back. It seems like the RS485 is disabled on the BMS or something?

There are also different protocols selectable compared to other pace bms versions out there. Do you know which would be the right one for Modbus?

![PXL_20230922_144444459](https://github.com/syssi/esphome-pace-bms/assets/5053729/342a80d1-544a-4a92-b19c-2179c217b3ec)

**Comment by Algram** [comment]
I got it working for the first pack by switching to a different version of the PBMS Tools software. This one had the protocol "Pace-Modbus" selectable.

How can I access multiple battery modules? I tried different slave addresses, but they are not found: 
![image](https://github.com/syssi/esphome-pace-bms/assets/5053729/7515d08c-a9e9-4ec8-b7dd-a6fd7612ebe6)

**Comment by hhoebel** [comment]
As fas as i understand the RS485-connection of the Pace-BMS, you only have access to the BMS to which you are connected. That means, you have to connect all your batteries with RS485 to read them out. You can either use one ESP32 per battery or connect all batteries togehter (use a simple RJ45-splitter with 1:1 connection at every battery and connect with the next battery) and add the additional batteries in the code of one ESP. In this case, it should work as listed above (address 0x1, address 0x2 etc.)

**Comment by ThHanika** [comment]
The RS485 protocol has to be PACE. If it isn't selectable, you have to take an other PC-software
![grafik](https://github.com/syssi/esphome-pace-bms/assets/41737282/2d5b9b18-1bb8-417e-a6e4-62959c4215a3)

My  software release: PbmsTools HS.1.0.7

**Comment by syssi** [comment]
This issue could be resolved by using an different version of the PBMS Tools software. The `PACE_MODBUS` protocol was available here.
