### ISSUE TITLE
Help for P16S100A, looks like PACE

### ISSUE THREAD

**Issue by Maikeleg** [syssi/esphome-pace-bms#19]
Hello,
I have read the topic/issue "Add PACE BMS support #1" and tried with the default "esp32-example.yaml" but can't get communication to work. My MQTT is working as i can see in the MQTT explorer. I got my battery in error with all experiments (luckily solved now) so I'm a bit more carefull now.
When i readout the pack with pbmstools i can only make connection with the version "Gobel_PC-BMS_Tools_HS2.0.3_Win32", i use rs485 on the parralel port. dip switch is set to 0, the dedicated rs485 next to can isnt working, other dipswitch settings are not working
However I see that address 0x01 is setup in the yaml. Do I need to change the pack dipswitch or change the yaml?
Also I use and only have the "esp32doit-devkit-v1" which i setup in yaml as: 
```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
```
is this correct? I see in the topic "Add PCA BMS support" only 8266 mentioned and a different board.
Also in your documentation you say to use orange/orange-white for B/A, however with pbmstools i can only communicate with brown/brown-white as B/A
I'm using a Joyvoit Suns Energy battery pack BW5KW: https://www.alibaba.com/product-detail/Energy-Power-wall-5-3-2kw_1600330104517.html
Using the pbmstools i get the VER readout: P16S100A-21468-1.00
Searching on google I think this is a PACE BMS, it also look like one, I can confirm it has 100A and 16 cells
Also I'm using the following RS485 3.3-5V module: https://a.aliexpress.com/_mt820MY

Is changing the address setting enough to make this work, and if so do I have to change the dipswitch on the pack or the setting in the yaml?
Sorry for all questions, I'm not experienced with ESP but would really like this to work
Greetings Maikel

**Comment by syssi** [comment]
1. Could you provide a photo of your RS485 converter Module?
2. Which GPIOs do you use as UART pins? Does the TX LED of the RS485 board blink periodically?
3. You could use the ESP+RS485 converter to capture some traffic between the BMS and the workstation. I would like to make sure the correct protocol (Modbus frames) are used here.
4. Yes. Have have to align the device address on both sides. If the BMS uses `0x00` you have to use the same address in the YAML.
5. You can ignore the `esp32.board` setting if you assign GPIOs at the YAML using `GPIOxx`. If you want to use the labels on the PCB like `D1, D2, D2,...` the setting is important.
6. Is there a drop-down menu available in pbmstools to choose between different protocols?

**Comment by Maikeleg** [comment]
Thanks a lot for your reply, i'll gather all information and come back to you as soon as possible

**Comment by Maikeleg** [comment]
> 1. Could you provide a photo of your RS485 converter Module?
> 
>     2. Which GPIOs do you use as UART pins? Does the TX LED of the RS485 board blink periodically?
> 
>     3. You could use the ESP+RS485 converter to capture some traffic between the BMS and the workstation. I would like to make sure the correct protocol (Modbus frames) is used here.
> 
>     4. Yes. Have have to align the device address on both sides. If the BMS uses `0x00` you have to use the same address in the YAML.
> 
>     5. You can ignore the `esp32.board` setting if you assign GPIOs at the YAML using `GPIOxx`. If you want to use the labels on the PCB like `D1, D2, D2,...` the setting is important.
> 
>     6. Is there a drop-down menu available in pbmstools to choose between different protocols?
1) This board;
![signal-2023-11-28-141542_002](https://github.com/syssi/esphome-pace-bms/assets/26905937/af19e200-c8e8-4aa7-93f0-e87a371a0ffb)
![signal-2023-11-28-141542_003](https://github.com/syssi/esphome-pace-bms/assets/26905937/65472ad1-a324-43f4-8ba9-12d7c091c882)
![signal-2023-11-28-141556_002](https://github.com/syssi/esphome-pace-bms/assets/26905937/effdb25c-8353-4712-9fb2-df585ba84a04)
2) GPIO 16+17 which should be UART 2 RX and UART 2 TX which i connected to RX-RX and TX-TX to the converter board
3) Could you tell me how to do that, connect the esp32 to usb-PC with converter board connected? 
4) I will try to change the yaml address and upload to the esp32 again later today 
5) Aah ok thanks
6) no there is not, it chooses that itself as it seems. Right under ADDR (Address) is shows
Protocol: None, HS-PC-232-BP-V1.1 (it is connected through RS485)

I'll check address and give you an update later today

**Comment by ThHanika** [comment]
The Modbus seems to need a configurated address to work, I use AddressNo. 1. (switch 1 set ON)
This example does the job. ( My impediments was wrong PIN-Selections on ESP-Board ;-P )

**Comment by Maikeleg** [comment]
> The Modbus seems to need a configurated address to work, I use AddressNo. 1. (switch 1 set ON) This example does the job. ( My impediments was wrong PIN-Selections on ESP-Board ;-P )
Ok thanks for your reply, I will set both to address 1. No time this evening but will try tomorrow morning

**Comment by ThHanika** [comment]
I use pbmstools with interface RS232. RS485 is the monitoring interface for me. With homeassistant and esphome, i can also change the parameter (but not all)

**Comment by Maikeleg** [comment]
> This sounds like good progress. You have to change the address at the YAML to `0x01` too. Otherwise the responses doesn't get picked up and decoded.

I also dont see any value in all the mqtt topics so I'm afraid its not being decoded
I also look at the topic in grafana via the mqtt plugin and see all information but again no value

**Comment by Maikeleg** [comment]
> FYI! The modbus-address 0x00 is a broadcast address and is not a valid slave-address

Do you mean by Slave address the battery pack address?? I only have one battery pack

**Comment by Maikeleg** [comment]
> The responses aren't valid Modbus frames. It looks like Seplos/Pylon responses. This reason could be one of the following options
> 
>     1. You've selected the wrong protocol at the RS485 protocol drop-down
> 
>     2. You are using the wrong port
> 
>     3. The BMS firmware doesn't support Modbus communication

Thanks for your quick reply
1. I cannot change the protocol settings (in pbmstools i think you mean?)
2. I tried all rs485 ports
3. I will ask the battery manufacturer if that's the case

Do you know by any chance if the seplos/pylon method also needs to be on pack 1? I tried that but only with dip 0
Changing both pack dip and yaml setting to 0x00 not going to work anyway or worth a try?

I'll check issue 17 now! Thanks a lot

**Comment by Maikeleg** [comment]
> This issue (#17) is about to the same problem.

Ok thanks again, I will try that tomorrow morning and let you know

**Comment by Maikeleg** [comment]
> I use pbmstools with interface RS232. RS485 is the monitoring interface for me. With homeassistant and esphome, i can also change the parameter (but not all)

I'm a bit in doubt what to do next. With whatever version of pbmstools I tried yesterday I cannot change the inverter setting. Most versions only work with pack 1-xx. The one that works for me is the Gobel 2.03HS. Can write parameters, readout current stats but cannot change inverter protocol. Seems that's only possible with a rs232??
Thing is that connector isn't on any of my pcs so have to buy another adapter for that. No problem but will cost quite some time
I have 8 different pbmstools to give you an idea and I'm running out of ideas to be honest
Thanks for your and the developpers help so far!! Much appreciated

**Comment by syssi** [comment]
Could you provide a screenshot of the `pbmstools` protocols section? Did you try to contact the seller / manufacturer?

**Comment by ThHanika** [comment]
... and you now the **special secret** password (123456) for changing settings?

**Comment by Maikeleg** [comment]
> Could you provide a screenshot of the `pbmstools` protocols section? Did you try to contact the seller / manufacturer?

I'll make tomorrow
Planning to contact the factory in Monday. Let you know tmr

**Comment by Maikeleg** [comment]
> ... and you now the **special secret** password (123456) for changing settings?

Yups have that. Is a specific password for other settings and one for inverter protocol

**Comment by ThHanika** [comment]
Look at andy's video canal:
https://www.youtube.com/watch?v=TbUUCXPN1Xg

**Comment by Maikeleg** [comment]
> Could you provide a screenshot of the `pbmstools` protocols section? Did you try to contact the seller / manufacturer?

![signal-2023-12-05-120334_002](https://github.com/syssi/esphome-pace-bms/assets/26905937/83d96c0b-d3d5-485b-aed8-37083f234f9c)
![signal-2023-12-05-120334_007](https://github.com/syssi/esphome-pace-bms/assets/26905937/61a60489-0d6e-4dcb-b272-e0fd95a9a2e6)
![signal-2023-12-05-120334_006](https://github.com/syssi/esphome-pace-bms/assets/26905937/ea427645-3805-4d67-8451-1cf4ffd0e33a)
![signal-2023-12-05-120334_005](https://github.com/syssi/esphome-pace-bms/assets/26905937/056f390a-43d1-4eba-936b-29581c7070ee)
![signal-2023-12-05-120334_004](https://github.com/syssi/esphome-pace-bms/assets/26905937/3a1b9836-1fec-4297-ba82-3125e96bfb27)
![signal-2023-12-05-120334_003](https://github.com/syssi/esphome-pace-bms/assets/26905937/0ec4e59b-1a6d-44e9-90f4-49502e935636)
If i change the xml file i also have an option with modbus protocol, i changed it back recently as one og the things to try
So as you can see i can readout all info except read or write inverter protocol
In the video that @ThHanika  Thomas posted (thanks a lot for that) i understand i need an rs232 cable

I sent a message to the company i bought the battery from, didn't got an answer yet, will ask them again

**Comment by ThHanika** [comment]
On the last picture, you have to click read under **Inverter protocol** to show selectet protocols

**Comment by Maikeleg** [comment]
> On the last picture, you have to click <Read> under **Inverter protocol** to show selected protocols
> 
> BTW: First you have generaly click <Read> before you can write any parameters, Pace expect complete filled parameterfield to update its parameter.

Hi Thomas,
I just talked to the lady in china who supports the battery, she says i need another firmware version and (ofcourse) discouraged me to change the setting. I'm waiting for her to email me. Keep you updated

**Comment by Maikeleg** [comment]
Just ordered these two cables, one with chipset according to a diysolar topic and one for SOK battery
![usb-rs232-rj11](https://github.com/syssi/esphome-pace-bms/assets/26905937/7706ad38-a6be-41ea-913e-ab944d13e973)

**Comment by Maikeleg** [comment]
I got all cable the day before going on holiday and all three of them didnt work out of the box
Since then I was out of country and busy getting back with things, I'll plan to continue this project probably monday morning and will report back
Supposedly i need a special driver for the direct connected cables so i have some things to try still

**Comment by Maikeleg** [comment]
I got it working with the following cable: SOK SK48V100 Battery RS232 serial communicatrion Prolific USB RS232 to RJ11 6P6C
I needed to update the serial driver for the prolific chipset PL2303GT on windows
Then set protocol to PACE_MODBUS in special version of Pbmstools that i got from factory 
After that i kept using this cable to readout the battery
Thanks for all help @syssi and @ThHanika

**Comment by theyo-tester** [comment]
@Maikeleg

May I Know which PBMSTool Version you used? Is it online somewhere available?

Thanks!

**Comment by Maikeleg** [comment]
> @Maikeleg
> 
> May I know which PBMSTool Version you used? Is it online somewhere available? My versions does not allow me to change the protocols....
> 
> Thanks!

So sorry I just read your reply now;
I got his version "PbmsTools HS1.0.6£¨¿ÉÑ¡Ð­Òé£©" which I'm almost 100% sure is the same as the version HS1.06
If you want it please let me know, i can sent it to you.
What makes the difference in being able to change protocol settings is using the RS232 interface with the right cable.
See above which i ordered ("Just ordered these two cables, one with chipset according to a diysolar topic and one for SOK battery") One of these is working (they look exactly the same so don't know which one)

I ended up keeping using the rs232 cable because it works reliably and i had a usb-port left :)

**Comment by tuxcrafter** [comment]
Could you please share a link to the Gobel_PC-BMS_Tools_HS2.0.3_Win32.zip tool? and did you get ESPHOME working, I got an P16S100A-21247-2.00 that I would like to communicate with.
