### ISSUE TITLE
Works with Meritsun

### ISSUE THREAD

**Issue by m1k3f15h** [syssi/esphome-pace-bms#29]
Hy,

The Project works also with a MeritSun LFP 200 - 48V (Rebranded by i-finity (company in Austria)).
Only had to Activate the Modbus via pbmstool.exe
@syssi if you want, you could add this to your Readme.

Thank's for the great Project :)

Greetings from Austria.
Mike

**Comment by syssi** [comment]
Cool! I'm happy about every contribution. Please extend the README.

**Comment by syssi** [comment]
See https://github.com/syssi/esphome-pace-bms/pull/30
